### ISSUE TITLE
How about making this a Poppins project?

### ISSUE THREAD

**Issue by tiagostutz** [flaviostutz/monolint#15]
Check this:
https://github.com/bancodobrasil/poppins/blob/master/MANIFESTO.md#guidelines-to-make-a-poppins-project

The idea of making this project follow the guidelines of a Poppins project is to make it really inviting for devs starting the career or even experienced devs that are actually starting in the open source world. Besides that, it is nice to have the badge on README file.

![This is a Poppins project](https://raw.githubusercontent.com/bancodobrasil/poppins/master/badge-poppins.svg)

**Comment by flaviostutz** [comment]
That would be nice! Let's do it! It think I already prepared some of the things. Be free to submit a PR with the changes to README file and CONTRIBUTING :)

**Comment by tiagostutz** [comment]
Noiice, thanks! 🎡
Please assign to me the task and I'll work on it
