### ISSUE TITLE
Create configuration bundle mechanism (like "extends" from eslint)

### ISSUE THREAD

**Issue by flaviostutz** [flaviostutz/monolint#25]
External parties should be able to create more complex set of configurations that could be reused.

For example, one could create a set of configurations specialized for Serverless Framework checks, such as checking if the "runtime" attribute of all serverless.yml files are the same in the project etc. It can help organizations share a common set of rules among monorepos also.

Our configuration would be:

```json

{
  "extends": ["monolint:recommended", "monolint:serverless", "plugin:somepluginname"],
  "rules": {
    "packagejson-same-name": true
  },
  "defaults": false -> WOULD BE REMOVED. by default "monolint:recommended" would activated and to deactivate everything one should only do "extends": []
}
```

(all the default configurations should be declared using the same mechanism also. The difference is that the "defaults" would be "default" activated bundles)

**Comment by tiagostutz** [comment]
Nice, I think that in fact we don't need the `defaults: false`. As you pointed, the `extends: []` will do the trick when users doesn't want the defaults.
