### ISSUE TITLE
Change from `make unit-test` to `make test`

### ISSUE THREAD

**Issue by tiagostutz** [flaviostutz/monolint#28]
I think it would be cleaner and simple as we don't have other type of test to just call `make test`. 
If we start having other types of test and it makes sense to run the tests separately, then we move back to `make unit-test`.

What do you think?

**Comment by flaviostutz** [comment]
I agree! Let’s do it!

**Comment by tiagostutz** [comment]
Cool, let's keep it opened for a while as this is a really "first-good-issue". If no one requests that, we tackle. 👍🏻

**Comment by RajputUsman** [comment]
Hi, could you check PR #30 if it satisfies the requirement for this issue?
