### ISSUE TITLE
When running "npx monolint ." in a repo without configuration error "module-markers are required" appears up

### ISSUE THREAD

**Issue by flaviostutz** [flaviostutz/monolint#35]
It seems this is due to not using default configuration, which is a bug

**Comment by sergioflores-j** [comment]
I ran into this issue while writing unit tests as well! Loading a configuration in a folder/path that doesn't exist throws that.

Shall we just suppress the error and use default configurations instead? Or throw a "missing configuration file" error?

**Comment by sergioflores-j** [comment]
I can pick this one up! :)
