### ISSUE TITLE
Create rule "module-required-files"

### ISSUE THREAD

**Issue by flaviostutz** [flaviostutz/monolint#4]
Check if modules have the specified files. Can be strict or not.

.monolinter.json:

* Enable rule and configure it for requiring file "README.md" and "Makefile"

```
{
  "rules": {
    "module-required-files": {
      "strict": false,
      "files": ["README.md", "Makefile"]
     }
  }
}
```

**Comment by tiagostutz** [comment]
As we already have "module-folder-structure" how about changing this module name to "module-required-files" to avoid mixing up both?

Also, what does "strict" means in this case? Means that it requires exactly the listed files and if there are other files than those it would be a violation?

**Comment by flaviostutz** [comment]
Good one! Strict means that only those files are allowed to be in the module.

**Comment by tiagostutz** [comment]
Cool! 
Please, can you assign this issue to me? I can tackle that.

**Comment by flaviostutz** [comment]
@tiagostutz I was wondering if, on top of the simpler way of describing required files, we could have a more advanced configuration like:

{
  "rules": {
    "module-required-files": {
      "strict": false,
      "files": [ 
         "README.md", "Makefile",
         {if: "package.json": ["tsconfig.json", "jest.config.js", ".eslintrc.js"] },
         {if: "go.mod": ["go.sum"] }
     }
  }
}

In this example, 
  - README.md and Makefile will be required for all modules
  - tsconfig.json, jest.config.js and .eslintrc.js only for modules that have file package.json
  - go.sum only for modules that have file go.mod
  
  This way we can have a good default for common languages.

**Comment by tiagostutz** [comment]
Sounds good! 
We could create another issue for that and keep this one with the simple configuration, as it will already bring value. 
And I have this small suggestion of change on top of what you proposed for the format. We could have the simple format (tackled in this ticket):
```bash
{
  "rules": {
    "module-required-files": {
      "strict": false,
      "files": ["README.md", "Makefile"]
     }
  }
```

And the advanced config:
```bash
{
   "rules":{
      "module-required-files":{
         "files":[
            {
               "all":[
                  "README.md",
                  "Makefile"
               ],
               "strict": false
            },
            {
               "package.json":[
                  "tsconfig.json",
                  "jest.config.js",
                  ".eslintrc.js"
               ],
               "strict": false
            },
            {
               "go.mod":[
                  "go.sum"
               ],
               "strict": true
            }
         ]
      }
   }
}
```

wdyt?

**Comment by flaviostutz** [comment]
Perfect! This proposal was moved to #20
