### ISSUE TITLE
Redesign idea: "Module markers" and auto discovery of modules

### ISSUE THREAD

**Issue by sergioflores-j** [flaviostutz/monolint#44]
The common approach for many (mono)repo tools for discovering modules is a glob pattern list.

See e.g. 
[npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces#defining-workspaces)

The proposal is to make this project similar to them in this perspective. So the users can have the same "mental model" across a different set of tools.

**Comment by sergioflores-j** [comment]
What do you think @flaviostutz? 

Shall we do it now (since the project is still in development) or we wait until we have collected some "real use case" data?

**Comment by flaviostutz** [comment]
I guess we could wait until having some real world use cases. But let's keep this in mind. This change would be easier to implement and probably wouldn't touch the rules (where could lead to a lot of work).

**Comment by flaviostutz** [comment]
Maybe we could add a label "evaluate-later" and close it for now?

**Comment by sergioflores-j** [comment]
Sounds good to me! :)

**Comment by sergioflores-j** [comment]
Won't fix for now!
