### ISSUE TITLE
Create rule "module-parent-folder"

### ISSUE THREAD

**Issue by flaviostutz** [flaviostutz/monolint#5]
Check if module is inside specific parent folder paths. Defaults to "modules"

.monolinter.json:

* Enable rule

```
{
  "rules": {
    "module-parent-folder": true
  }
}
```

* Enable rule with custom parent names

```
{
  "rules": {
    "module-parent-regex": ["services", "web", "libs", "services/group1", "services/group2"]
  }
}
```

**Comment by tiagostutz** [comment]
Hi! I'm taking this for my Open Source Friday...

**Comment by flaviostutz** [comment]
🎉🎉

**Comment by tiagostutz** [comment]
I think it would make sense to have the `module-parent-folder` being either a boolean or the array of regex instead of having two different attributes, right?
Like:
**Boolean:**
```json
{
  "rules": {
    "module-parent-folder": true
  }
}
```

**Regex:**
```json
{
  "rules": {
    "module-parent-folder": ["services", "web", "libs", "services/group1", "services/group2"]
  }
}
```

Right?

**Comment by tiagostutz** [comment]
Also, I'm not sure if it in this case having a default value makes sense... because this type of structure is very wide IMO. Maybe it would be better to have it just as an array of glob patterns.
wdyt?

**Comment by flaviostutz** [comment]
An array of glob patterns is perfect and very powerful! Maybe the default could be “modules”, what do you think?

About glob processing, we use it on discovermodules already using “fast-glob”. Take a look while implementing it.

**Comment by tiagostutz** [comment]
Nice, thanks for the `fast-glob` tip, I'll check that out! Very handy.

About the default `modules` folder, still not sure if there is enough common sense that a project would have `modules` as the parent folder of the created modules. For instance, in https://github.com/vsavkin/large-monorepo we don't have it and in some of the projects at https://github.com/korfuri/awesome-monorepo#notable-public-monorepos I couldn't find a common sense. I still think that this lack of common sense/practice leads to not having a default approach so far.

My suggestion is to start without the default as it simplifies a little bit the code, and then we discuss this in another issue. Sounds reasonable?

**Comment by flaviostutz** [comment]
Ok! Let's do that.
